# Generated by Django 4.2.2 on 2023-06-11 19:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ticket', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserRole',
        ),
    ]
