# Generated by Django 4.2.2 on 2023-06-11 19:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('ticket', '0002_delete_userrole'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='agent',
            field=models.ForeignKey(blank=True, limit_choices_to={'ticket_admin': True, 'ticket_agent': True}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='agent_tickets', to=settings.AUTH_USER_MODEL),
        ),
    ]
