# Generated by Django 4.2.2 on 2023-06-11 19:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ticket', '0003_alter_ticket_agent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='completed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
